### ISSUE TITLE
does not open default phone app (Koler)

### ISSUE THREAD

**Issue by RemyBorius** [Bnyro/ConnectYou#109] opened 2023-03-17 17:59 UTC
### Steps to reproduce

When i select a contact and push the phone button, it tries to open my default phone app (which is Koler, super cool open source phone app), but fails. 

I think it's Connect you that host the problem cause phone call from google contact works well.

Thanks for your work btw

### Expected behavior

Call works with  default phone app

### Actual behavior

Crash

### Connect You version

2.3

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RemyBorius** [comment] 2023-03-17 18:00
Just saw it's Koler problem sry

**Comment by Bnyro** [comment] 2023-03-17 18:07
yes, duplicate of #101

**Closed by Bnyro** 2023-03-17 18:07 UTC
Labels: bug

**Comment by scottbetza** [comment] 2023-03-18 23:46
@Bnyro I think I figured it out. Can you double check your app supports number longer than 12 character in length and has IDD and country code support?

For example, if you're from U.S. try +1 719-266-2837. Should crash.

Edit to just be 719-266-2837. Now it should work.

Or recreate the IDD and country with whatever country your in. Germany would be +49, so +49 651 41178 for example, but that might work since it's short than U.S. number.

```
03-18 19:24:38.498 E/AndroidRuntime(30223): Process: com.chooloo.www.koler, PID: 30223
03-18 19:24:38.498 E/AndroidRuntime(30223): java.lang.RuntimeException: Unable to resume activity {com.chooloo.www.koler/com.chooloo.www.koler.ui.main.MainActivity}: java.lang.IndexOutOfBoundsException: setSpan (13 ... 13) ends beyond length 12
03-18 19:24:38.503 I/am_crash( 1972): [30223,0,com.chooloo.www.koler,550026820,java.lang.IndexOutOfBoundsException,setSpan (13 ... 13) ends beyond length 12,SpannableStringBuilder.java,1326]
03-18 19:24:38.506 I/wm_finish_activity( 1972): [0,243437852,746,com.chooloo.www.koler/.ui.main.MainActivity,force-crash]
```

**Comment by Bnyro** [comment] 2023-03-19 07:30
Well, as you can see in the logs Koler doesn't support it and crashes, not Connect You.

**Comment by scottbetza** [comment] 2023-03-19 12:18
> Well, as you can see in the logs Koler doesn't support it and crashes, not Connect You.

Sorry i was running low on energy yesterday. You're right so I'd like to put in a ticket to koler dev but just want to confirm one thing that may help them.

The android stock contacts app to koler works fine with IDD and country codes +1 xxx-xxx-xxxx. So the android stock contacts app send it differently than connect you somehow it seems.

Can you try a number I have above and let me know how connect you passes the string to the default dialer (e.g., "+1 719-266-2837" becomes "+17192662837"). I think that will be important for my issue submission to koler.

**Comment by Bnyro** [comment] 2023-03-19 12:29
Connect You currently passes the number exactly as chosen by the user, so for example "+49 176-608-7568" would be passed exactly like that. However, if that resolves the issue we can remove all blank spaces and all occurrences of "-" on Connect You's side.

**Comment by scottbetza** [comment] 2023-03-19 12:46
Thanks I opened issue with them.

https://github.com/Chooloo/koler/issues/520

One last item since you use koler as well. Could you just confirm your koler app crashes too with the number +1 719-266-2837?

**Comment by Bnyro** [comment] 2023-03-19 13:01
Yes, I can confirm that. It seems to be caused by the empty space after the `1` which Koler doesn't seem to handle properly. I've tested it without the empty space and Koler behaves as expected now. I guess we can just remove blank spaces from the number before passing it to the dialer app the user has installed, if you can confirm that seems to fix the issue?

**Comment by scottbetza** [comment] 2023-03-19 14:34
Thanks for checking! Yep removing the space solves it for me. 

I'd recommend not modifying it personally. 

Koler should accept phone numbers according to the [ITU E.123 srandard](https://www.itu.int/rec/T-REC-E.123-200102-I/en) which has a space between country code and trunk code.

Well I have an easy work around though. Will just run some formulas on my contact list an re-import.
