### ISSUE TITLE
Directly opening contact instead opening a list of all contacts

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/ConnectYou#34] opened 2023-02-04 12:41 UTC
When I click to contact in dialer, it shows me a list of all contacts, but not the contact I've clicked

**Comment by Bnyro** [comment] 2023-02-04 12:45
Can't reproduce using Koler

**Comment by HotarunIchijou** [comment] 2023-02-04 12:49
@Bnyro you can reproduce it using lineageos dialer and simple dialer

**Comment by Bnyro** [comment] 2023-02-04 15:30
seems to be fixed with https://github.com/Bnyro/ConnectYou/commit/c6056ba267f623a2742b8a08a309655efc3270ef
(tested with the dialer app of LineageOS)

**Closed by Bnyro** 2023-02-04 15:30 UTC
