### ISSUE TITLE
Contacts problem

### ISSUE THREAD

**Issue by muznyo** [Bnyro/ConnectYou#5] opened 2023-01-28 09:11 UTC
I dont know if its because i use davx5 for contacts or because my contacts have letters like this - čěá for example, but those contacts keep showing up like this
![Screenshot_20230128-100913_Connect You](https://user-images.githubusercontent.com/24987471/215257630-a86e5614-1d60-4e0f-a897-056182c27aac.png)

**Comment by Bnyro** [comment] 2023-01-28 09:39
duplicate of #2

**Closed by Bnyro** 2023-01-28 09:39 UTC

**Comment by airon90** [comment] 2023-01-28 22:47
This problem occurs to me again after 0.2.0 has been published

**Comment by Bnyro** [comment] 2023-01-29 07:18
I've been told by some others that the issue doesn't persist anymore for them, so an example "name" of a wrongly displayed contact would be good.

**Comment by muznyo** [comment] 2023-01-29 09:47
i still see wrong names and contacts and sorting doesnt work, if i try to edit their name it doesnt apply and still has the old name with numbers
